apiVersion: v1
data:
  defaults.ini: |
    [server]
    #protocol = http
    #http_addr =
    #domain = localhost
    #enforce_domain = false
    #root_url = %(protocol)s://%(domain)s:%(http_port)s/
    [analytics]
    check_for_updates = true
    [auth.ldap]
    allow_sign_up = true
    config_file = /root/grafana/conf/ldap.toml
    enabled = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /root/grafana/data
    logs = /root/grafana/data/log
    plugins = /root/grafana/data/plugins
    provisioning = /root/grafana/conf/provisioning
kind: ConfigMap
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: ops-monitor
