apiVersion: v1
data:
  defaults.ini: |
    [analytics]
    check_for_updates = true
    [auth.ldap]
    allow_sign_up = true
    config_file = /root/grafana/confldap.toml
    enabled = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /root/grafana/data
    logs = /root/grafana/data/log
    plugins = /root/grafana/data/plugins
    provisioning = /root/grafana/conf/provisioning
kind: ConfigMap
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: ops-monitor
