apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: grafana
  name: grafana
  namespace: ops-monitor
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: grafana
  #strategy:
  #  rollingUpdate:
  #    maxSurge: 25%
  #    maxUnavailable: 25%
  #  type: RollingUpdate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: /base/grafana:5.3.4
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/health
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        name: grafana
        ports:
        #- containerPort: 80
        #  name: service
        #  protocol: TCP
        - containerPort: 3000
          name: grafana
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /api/health
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 4000m
            memory: 4Gi
          requests:
            cpu: 2000m
            memory: 1024Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/grafana/data
          name: storage
        - mountPath: /root/grafana/conf/provisioning
          name: provisioning
        - mountPath: /root/grafana/conf/defaults.ini
          name: config
          subPath: defaults.ini
        - mountPath: /root/grafana/conf/ldap.toml
          name: ldap
          subPath: ldap.toml
      dnsPolicy: ClusterFirst
      #nodeName: cn-beijing.i-2ze2wzpijgvf1h74wnyr
      nodeName: cn-beijing.i-2ze9ymgoq8jp13vnnn4g
      schedulerName: default-scheduler
      #serviceAccount: grafana
      #serviceAccountName: grafana
      terminationGracePeriodSeconds: 30
      volumes:
      - name: storage
        hostPath:
          path: /data/grafana
          type: DirectoryOrCreate
      - name: provisioning
        hostPath:
          path: /data/grafana/conf/provisioning
          type: DirectoryOrCreate
      - configMap:
          #defaultMode: 0777
          name: grafana
        name: config
      - name: ldap
        secret:
          #defaultMode: 0777
          items:
          - key: ldap-toml
            path: ldap.toml
          secretName: grafana
