apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.name}}
  name: {{.name}}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: {{.name}}
  type: NodePort