apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
  namespace: ops
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - date;echo  Hello from the Kubernetes cluste
            image: hub/base/centos:7.4
            imagePullPolicy: Always
            name: hello
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          terminationGracePeriodSeconds: 30
  schedule: '*/1 * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
