apiVersion: v1
kind: Service
metadata:
  name: kafka-manager-new
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: kafka-manager
  sessionAffinity: None
  type: LoadBalancer