apiVersion: v1
kind: Pod
metadata:
  name: test-cm-pod
  namespace: kube-test
spec:
  containers:
    - name: test-container
      image: docker.io/nginx:latest
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: base-rules
  restartPolicy: Never
