alerting:
  alertmanagers:
  - static_configs:
    - targets: ['10.10.9.95:80']
global:
  evaluation_interval: 30s
  external_labels: {monitor: codelab-monitor}
  scrape_interval: 30s
rule_files: [rules/*.rules]
scrape_configs:
- job_name: mp-videovv-count-consumer
  metrics_path: /metrics
  static_configs:
  - targets: ['192.168.132.85:9100', '192.168.132.75:9100', '192.168.132.83:9100',
      '192.168.132.84:9100', '192.168.132.76:9100']
