kind: Service
apiVersion: v1
metadata: 
  name: {{.name}}
  labels: 
    app: {{.name}}
  annotations: 
    service.beta.kubernetes.io/alicloud-loadbalancer-address-type: intranet
{{ if index . "slb_id" }}
    service.beta.kubernetes.io/alicloud-loadbalancer-id: {{.slb_id}}
{{ end }}
spec: 
  ports: 
    - name: {{.name}}-service
      protocol: TCP
      port: 389
      targetPort: 389
{{ if index . "node_port_ldap" }}
      nodePort: {{.node_port_ldap}}
{{ end }}
    - name: "{{.name}}-admin"
      protocol: TCP
      port: 80
      targetPort: 80
{{ if index . "node_port_ldap_admin" }}
      nodePort: {{.node_port_ldap_admin}}
{{ end }}
  selector: 
    app: {{.name}}
  type: LoadBalancer