kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{.name}}-data
  annotations:
    volume.beta.kubernetes.io/storage-class: "alicloud-disk-ssd"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "{{.storage_size}}"
{{ if index . "volume_name" }}
  volumeName: {{.volume_name}}
{{ end }}