apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alicloud-loadbalancer-address-type: intranet
{{ if index . "slb_id" }}
    service.beta.kubernetes.io/alicloud-loadbalancer-protocol-port: {{.slb_port}}
    service.beta.kubernetes.io/alicloud-loadbalancer-id: {{.slb_id}}
{{ end }}
  name: {{.name}}
  labels:
    app: {{.name}}
spec:
  type: LoadBalancer
  ports:
  - name: ssh
    port: 22
    targetPort: ssh
{{ if index . "node_port_ssh" }}
    nodePort: {{.node_port_ssh}}
{{ end }}
  - name: http
    port: 80
    targetPort: http
{{ if index . "node_port_http" }}
    nodePort: {{.node_port_http}}
{{ end }}
  - name: https
    port: 443
    targetPort: https
{{ if index . "node_port_https" }}
    nodePort: {{.node_port_https}}
{{ end }}
  selector:
    app: {{.name}}

