apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gitlab
    spec:
{{ if index . "init" }}
      initContainers:
      - name: init-kong-pgsql
        image: postgres:10.4
        env:
          - name: KONG_PG_USER
            value: {{.pg_user}}
          - name: KONG_PG_DB
            value: {{.pg_db}}
          - name: KONG_PG_PASSWD
            value: {{.pg_passwd}}
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{.pg_host}}
                key: postgresql-password
        command: 
          - sh
          - -cx
          - psql -p5432 -h{{.pg_host}} -Upostgres -c "CREATE DATABASE $KONG_PG_DB;"; psql -p5432 -h{{.pg_host}} -Upostgres -c "CREATE USER $KONG_PG_USER WITH PASSWORD '$KONG_PG_PASSWD';GRANT ALL PRIVILEGES ON DATABASE "$KONG_PG_DB" to $KONG_PG_USER;"; echo 'db inited...'
{{ end }}         
      containers:
      - name: gitlab
        image: {{.image}}
        env:
        ## General GitLab Configs
        ##
        # This is a free-form env var that GitLab Omnibus uses to configure
        # everything. We're passing this in from a configmap and pulling some
        # of the values from the env vars defined below. This is done to
        # avoid leaving secrets visible in kubectl.
        - name: GITLAB_OMNIBUS_CONFIG
          valueFrom:
            configMapKeyRef:
              name: gitlab
              key: gitlab_omnibus_config
        - name: GITLAB_ROOT_PASSWORD
        - name: EXTERNAL_URL
          value: "{{.public_url}}"
        ## DB configuration
        ##
        - name: DB_HOST
          value: {{.pg_host}}
        - name: DB_USER
          value: {{.pg_user}}
        - name: DB_PASSWORD
          value: {{.pg_passwd}}
        - name: DB_DATABASE
          value: {{.pg_db}}
        ## Redis configuration
        ##
        - name: REDIS_HOST
          value: redis-{{.name}}
        - name: REDIS_PASSWORD
          value: changeit
        #   valueFrom:
        #     secretKeyRef:
        #       name: gitlab
        #       key: redis-password
        ports:
        - name: ssh
          containerPort: 22
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /help
            port: http
          # This pod takes a very long time to start up. Be cautious when
          # lowering this value to avoid Pod death during startup.
          initialDelaySeconds: 200
          timeoutSeconds: 1
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /help
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        volumeMounts:
        - name: gitlab-data
          mountPath: /etc/gitlab
          subPath: gitlab-etc
        - name: gitlab-data
          mountPath: /gitlab-data
          subPath: gitlab-data
        resources:
          limits:
            cpu: 2
            memory: 8Gi
          requests:
            cpu: 500m
            memory: 1Gi
          
      volumes:
      - name: gitlab-data
        persistentVolumeClaim:
          claimName: {{.name}}-data
