apiVersion: v1
kind: Service
metadata:
  labels:
    app: zk-svc
  name: zk-svc
spec:
  clusterIP: None
  ports:
  - name: server
    port: 2888
    protocol: TCP
    targetPort: 2888
  - name: leader-election
    port: 3888
    protocol: TCP
    targetPort: 3888
  selector:
    app: zk
  sessionAffinity: None
  type: ClusterIP