apiVersion: v1
kind: Service
metadata:
  name: mp-sre-logstash
  namespace: ops
spec:
  ports:
  - name: serviceport
    port: 80
  selector:
    service: mp-sre-logstash
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mp-sre-logstash-few
  namespace: ops
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kafka-mp-service-ssp-proxy
        service: mp-sre-logstash
    spec:
      containers:
        - name: mp-sre-logstash-redis-mp-service-passport
          image: hub/ops/mp-sre-logstash:redis_mp_service_passport
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
