apiVersion: v1
data:
  my.cnf: "[client]\nport        = 3306\n[mysqld_safe]\nopen-files-limit = 65535\nnice\t=
    0\n[mysqld]\nuser\t= mysql\nport        = 3306\ndefault-storage-engine=InnoDB\ncharacter_set_server
    \   = utf8\ncollation_server        = utf8_general_ci\n#explicit_defaults_for_timestamp
    = true\nmax_connections=1500\nskip-external-locking\n#key_buffer_size = 64M\nbulk_insert_buffer_size
    = 64M\nmax_allowed_packet = 32M\ntable_open_cache = 3600\nopen_files_limit=65535\ntmp_table_size=256M\nsort_buffer_size
    = 4M\nread_buffer_size = 16M\nquery_cache_min_res_unit = 2k\nread_rnd_buffer_size
    = 16M\nmyisam_sort_buffer_size = 128M\nthread_handling\t\t= pool-of-threads\nthread_pool_oversubscribe
    = 10\ninteractive_timeout = 600\nwait_timeout        = 300\nback_log            =
    1000\nmax_connections     = 1000\nmax_connect_errors  = 2000\nthread_cache_size
    = 256\nquery_cache_type=1\nquery_cache_size= 128M\ntransaction_isolation =  READ-COMMITTED\ninnodb_buffer_pool_size
    = 1024M\nskip-name-resolve\n#innodb_buffer_pool_instances = 8\ninnodb_file_per_table
    = 1\n#datadir = /data/mydata\n#log-bin=/data/binlogs/mysql-bin\nexpire_logs_day=30\nmax_binlog_size
    = 200M\nslow_query_log=ON\n#slow-query-log-file=/data/binlogs/slow_query.log\nlong_query_time=2\nlog-slow-admin-statements
    = 0\nlog_bin_trust_function_creators=1\nbinlog_format=row\nlog-bin=/var/lib/mysql/mysql-bin\nsync_binlog
    \    = 0\nserver-id   = 1\ninnodb_write_io_threads = 8\ninnodb_read_io_threads
    = 16\ninnodb_flush_log_at_trx_commit = 2\ninnodb_log_files_in_group = 2\ninnodb_max_dirty_pages_pct
    = 60\ninnodb_flush_method     = O_DIRECT\ninnodb_flush_neighbors  = 1\ninnodb_adaptive_flushing
    = 1\n#innodb_adaptive_flushing_method = \"estimate\"\ninnodb_adaptive_hash_index
    = 1\ninnodb_lock_wait_timeout = 60\ninnodb_io_capacity      = 8000\n#innodb_file_format
    \    = barracuda\n#innodb_file_format_max = barracuda\n#innodb_commit_concurrency
    = 1\n#innodb_page_size       = 8k\n#innodb_checksums       = 0\ninnodb_doublewrite
    \     = 0\ninnodb_support_xa       = 1\ninnodb_use_native_aio   = 1\ninnodb_stats_persistent
    = 1\ninnodb_purge_threads    = 1\ninnodb_sync_spin_loops  = 100\ninnodb_spin_wait_delay
    \ = 30\ninnodb_old_blocks_time  = 1000\ninnodb_old_blocks_pct   = 60\ninnodb_open_files
    \      = 4096\n[mysqldump]\nquick\nmax_allowed_packet = 64M\n[mysql]\nno-auto-rehash\n[myisamchk]\nkey_buffer_size
    = 64M\nsort_buffer_size = 512M\nread_buffer = 256M\nwrite_buffer = 256M\n[mysqlhotcopy]\ninteractive-timeout"
kind: ConfigMap
metadata:
  name: mysql-etc-configmap