apiVersion: v1
kind: Service
metadata:
  name: mysql-server-new-svc
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  sessionAffinity: None
  type: LoadBalancer