apiVersion: v1
kind: Service
metadata:
  name: mysql-server
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: mysql
    nodePort: 30324
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  sessionAffinity: None
  type: NodePort